[package]
name = "hubcaps"
version = "0.2.8"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Rust interface for Github"
documentation = "https://softprops.github.io/hubcaps"
homepage = "https://github.com/softprops/hubcaps"
repository = "https://github.com/softprops/hubcaps"
keywords = ["hyper", "github"]
license = "MIT"

[dev-dependencies]
env_logger = "0.3"


[dependencies]
log = "0.3"
hyper = "0.10"
hyper-openssl = "0.2"
url = "1.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
serializable_enum = "0.3"
