name: Main

on: push

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
          rust-version: nightly
      - uses: actions/checkout@v2
      - run: cargo fmt --all -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - uses: actions/checkout@v2
      - run: cargo clippy --all-targets -- -D clippy::all

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2
      - run: cargo check --all

  test:
    needs: [codestyle, lint, compile]
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    runs-on: ubuntu-latest

    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: cargo test
  publish-docs:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2
      - name: Generate Docs
        shell: bash
        run: |
          cargo doc --no-deps
          echo "<meta http-equiv=refresh content=0;url=`echo ${{ github.repository  }} | cut -d / -f 2 | tr '-' '_'`/index.html>" > target/doc/index.html
      - name: Publish
        if: github.ref == 'refs/heads/master' && env.PERSONAL_TOKEN
        uses: docker://peaceiris/gh-pages:v2.3.1
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/doc
          PERSONAL_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        with:
          emptyCommits: true

  publish-crate:
    if: startsWith(github.ref, 'refs/tags/') && env.CRATES_TOKEN
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2
      - name: Publish
        shell: bash
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
        env:
          CRATES_TOKEN: {{ secrets.CRATES_TOKEN }}